# Generated by Django 4.2.7 on 2023-11-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.CharField(blank=True, db_column='description', max_length=500, null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=100, null=True)),
                ('video_conferencing', models.BooleanField(db_column='video_conferencing')),
                ('duration', models.DurationField(db_column='duration')),
                ('deadline', models.DateTimeField(db_column='deadline')),
                ('creation_date', models.DateTimeField(db_column='creation_date')),
                ('passcode', models.CharField(db_column='passcode', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePool',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('voting_start_date', models.DateTimeField()),
                ('voting_deadline', models.DateTimeField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(db_column='end_date')),
                ('schedule_pool_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedulepool')),
            ],
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('preference', models.CharField(db_column='preference', max_length=100)),
                ('time_slot', models.ForeignKey(db_column='time_slot', on_delete=django.db.models.deletion.CASCADE, to='api.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='final_date',
            field=models.ForeignKey(blank=True, db_column='final_date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.timeslot'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_type_id',
            field=models.ForeignKey(blank=True, db_column='video_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.videotype'),
        ),
    ]
