# Generated by Django 4.2.7 on 2023-12-09 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def add_preferences(apps, schema_editor):
    CHOICES = ("YES", "MAYBE","NO")

    Preference = apps.get_model('api', 'Preference')

    for choice in CHOICES:
        prefrence = Preference(description=choice)
        prefrence.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('message', models.CharField(db_column='message', max_length=1500)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.CharField(blank=True, db_column='description', max_length=500, null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=100, null=True)),
                ('video_conferencing', models.BooleanField(db_column='video_conferencing')),
                ('duration', models.DurationField(db_column='duration')),
                ('deadline', models.DateTimeField(db_column='deadline')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('passcode', models.CharField(db_column='passcode', max_length=5)),
                ('user_nickname', models.CharField(blank=True, db_column='user_nickname', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(choices=[('YES', 'YES'), ('MAYBE', 'MAYBE'), ('NO', 'NO')], db_column='description', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePool',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('voting_start_date', models.DateTimeField()),
                ('voting_deadline', models.DateTimeField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(db_column='end_date')),
                ('schedule_pool', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedulepool')),
            ],
            options={
                'unique_together': {('schedule_pool', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('preference', models.CharField(db_column='preference', max_length=100)),
                ('user_nickname', models.CharField(blank=True, db_column='user_nickname', max_length=20, null=True)),
                ('time_slot', models.ForeignKey(db_column='time_slot', on_delete=django.db.models.deletion.CASCADE, to='api.timeslot')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePoolLink',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_column='token', default=uuid.uuid4)),
                ('schedule_pool', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedulepool')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='final_date',
            field=models.ForeignKey(blank=True, db_column='final_date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.timeslot'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('file', models.FileField(db_column='file', upload_to='feedback/')),
                ('feedback', models.ForeignKey(blank=True, db_column='feedback_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.feedback')),
            ],
        ),
        migrations.RunPython(add_preferences),
    ]
