# Generated by Django 4.2.7 on 2023-12-10 14:48

from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings


class Migration(migrations.Migration):
    
    def add_preferences(apps, schema_editor):
        CHOICES = ("YES", "MAYBE","NO")

        Preference = apps.get_model('api', 'Preference')

        for choice in CHOICES:
            prefrence = Preference(description=choice)
            prefrence.save()

    def add_user(apps, schema_editor):
        User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
        User.objects.create(username=settings.ANONYMOUS_USERNAME)


    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_preferences),
        migrations.RunPython(add_user),
    ]
