# Generated by Django 4.2.7 on 2023-12-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(db_column='end_date')),
                ('preference', models.CharField(db_column='preference', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='participantpreference',
            name='selected_timeslots',
        ),
        migrations.DeleteModel(
            name='CustomTimeSlot',
        ),
        migrations.DeleteModel(
            name='ParticipantPreference',
        ),
    ]
