# Generated by Django 4.2.7 on 2023-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
    ]
