# Generated by Django 4.2.7 on 2023-12-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(choices=[('YES', 'YES'), ('MAYBE', 'MAYBE'), ('NO', 'NO')], db_column='description', max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='feedbackattachment',
            old_name='feedback_id',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='video_type_id',
            new_name='video_type',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='schedule_pool_id',
            new_name='schedule_pool',
        ),
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user_nickname',
            field=models.CharField(blank=True, db_column='user_nickname', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='user_nickname',
            field=models.CharField(blank=True, db_column='user_nickname', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SchedulePoolLink',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_column='token', default=uuid.uuid4)),
                ('schedule_pool', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedulepool')),
            ],
        ),
    ]
