# Generated by Django 4.2.7 on 2023-12-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_delete_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
