# Generated by Django 4.2.7 on 2023-12-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback_feedbackattachment'),
        ('api', '0005_delete_user'),
    ]

    operations = [
    ]
