# Generated by Django 4.2.7 on 2023-12-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20231205_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], default='yes', max_length=10)),
                ('selected_timeslots', models.ManyToManyField(to='api.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('preference', models.CharField(default='yes', max_length=10)),
                ('participant_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='api.participantpreference')),
            ],
        ),
    ]
